version: 2
image: ubuntu:16.04
jobs:
  build:
    docker:
      - image: node:latest

    working_directory: ~/repo

    steps:
      - checkout

      # - restore_cache:
      #     keys:
      #     - yarn-cache

      - run: |
          yarn global add create-react-app
          yarn install
          create-react-app --scripts-version file:/$(pwd) testapp
          cd testapp
          npm run test
          npm run build

      # - save_cache:
      #     paths:
      #       - ~/.yarn-cache
      #     key: yarn-cache

